/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-08-12 10:58:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005f03_005fajax_005fjoin_005fmysql;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<table id=\"content-join\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"3\" id=\"title\"><h2>회원가입</h2></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"2\">아이디</td>\r\n");
      out.write("            <td><input id=\"input-memberId\" type=\"text\" placeholder=\"아이디를 입력해주세요\" value=\"test1234\"></td>\r\n");
      out.write("            <td><button id=\"button-memberIdCheckPro\">중복확인</button></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td id=\"msg-memberId\" colspan=\"2\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"2\">비밀번호</td>\r\n");
      out.write("            <td colspan=\"2\"><input id=\"input-memberPw\" type=\"text\" placeholder=\"비밀번호를 입력해주세요\" value=\"Test1234!\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td id=\"msg-memberPw\" colspan=\"2\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"2\">비밀번호확인</td>\r\n");
      out.write("            <td colspan=\"2\"><input id=\"input-memberPwRe\" type=\"text\" placeholder=\"비밀번호를 한번 더 입력해주세요\" value=\"Test1234!\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td id=\"msg-memberPwRe\" colspan=\"2\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"2\">이름</td>\r\n");
      out.write("            <td colspan=\"2\"><input id=\"input-memberName\" type=\"text\" placeholder=\"이름을 입력해주세요\" value=\"고유동\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td id=\"msg-memberName\" colspan=\"2\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"2\">이메일</td>\r\n");
      out.write("            <td><input id=\"input-memberEmail\" type=\"text\" placeholder=\"이메일을 입력해주세요\" value=\"test1234@naver.com\"></td>\r\n");
      out.write("            <td><button id=\"button-memberEmailCheckPro\">중복확인</button></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td id=\"msg-memberEmail\" colspan=\"2\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"2\">휴대폰</td>\r\n");
      out.write("            <td colspan=\"2\"><input id=\"input-memberPhone\" type=\"text\" placeholder=\"숫자만 입력해주세요\" value=\"01012345678\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td id=\"msg-memberPhone\" colspan=\"2\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"2\">우편번호</td>\r\n");
      out.write("            <td><input id=\"input-memberAddr1\" type=\"text\" placeholder=\"우편번호를 입력해주세요\" value=\"02830\"></td>\r\n");
      out.write("            <td><button onclick=\"execDaumPostcode()\">우편번호검색</button></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td id=\"msg-memberAddr1\" colspan=\"2\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"2\">도로명 주소</td>\r\n");
      out.write("            <td colspan=\"2\"><input id=\"input-memberAddr2\" type=\"text\" placeholder=\"도로명 주소를 입력해주세요\" value=\"서울 성북구 아리랑로 3\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td id=\"msg-memberAddr2\" colspan=\"2\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"2\">남은 주소</td>\r\n");
      out.write("            <td colspan=\"2\"><input id=\"input-memberAddr3\" type=\"text\" placeholder=\"남은 주소를 입력해주세요\" value=\"남은주소\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td id=\"msg-memberAddr3\" colspan=\"2\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>성별</td>\r\n");
      out.write("            <td colspan=\"2\">\r\n");
      out.write("                <label><input type=\"radio\" class=\"radio-memberGender\" name=\"gender\" value=\"1\">남자</label>\r\n");
      out.write("                <label><input type=\"radio\" class=\"radio-memberGender\" name=\"gender\" value=\"2\">여자</label>\r\n");
      out.write("                <label><input type=\"radio\" class=\"radio-memberGender\" name=\"gender\" value=\"0\" checked>선택안함</label>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>유입 경로</td>\r\n");
      out.write("            <td colspan=\"2\">\r\n");
      out.write("                <select id=\"select-memberRoute\">\r\n");
      out.write("                    <option value=\"1\">인터넷 검색</option>\r\n");
      out.write("                    <option value=\"2\">지인 권유</option>\r\n");
      out.write("                    <option value=\"3\">SNS</option>\r\n");
      out.write("                    <option value=\"4\">광고</option>\r\n");
      out.write("                    <option value=\"0\" selected>기타</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td rowspan=\"2\">이용약관동의</td>\r\n");
      out.write("            <td colspan=\"2\">\r\n");
      out.write("                <label><input id=\"check-memberAllTerms\" type=\"checkbox\">전체 동의</label>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"2\">\r\n");
      out.write("                <label><input class=\"check-memberTerms\" type=\"checkbox\" value=\"1\">이용약관 동의 (필수)<br></label>\r\n");
      out.write("                <label><input class=\"check-memberTerms\" type=\"checkbox\" value=\"2\">개인정보취급 동의 (필수)<br></label>\r\n");
      out.write("                <label><input class=\"check-memberTerms\" type=\"checkbox\" value=\"3\">만 14세 이상입니다. (필수)<br></label>\r\n");
      out.write("                <label><input class=\"check-memberTerms select-memberTerm\" type=\"checkbox\" value=\"0\">마케팅 메일 수신 동의 (선택)<br></label>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"3\" id=\"joinPro\">\r\n");
      out.write("                <button id=\"button-memberJoinPro\">가입하기</button>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    	\r\n");
      out.write("    		 /* 아이디 유효성 검사 */\r\n");
      out.write("            let inputMemberIdInput = (event) => {\r\n");
      out.write("                let $msgMemberId = document.querySelector(\"#msg-memberId\");\r\n");
      out.write("\r\n");
      out.write("                let regExp = RegExp(/^[A-Za-z0-9_\\-]{6,16}$/);\r\n");
      out.write("                if(regExp.test($inputMemberId.value)) {\r\n");
      out.write("                    $msgMemberId.innerHTML = \"\";\r\n");
      out.write("                } else {\r\n");
      out.write("                    $msgMemberId.innerHTML = \"<span style='color:#F03F40; font-size:12px;'>6자 이상 16자 이하의 영문 혹은 영문과 숫자를 조합</span>\";\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* 아이디 중복검사 */\r\n");
      out.write("            let buttonMemberIdCheckProClick = (event) => {\r\n");
      out.write("                let regExp = RegExp(/^[A-Za-z0-9_\\-]{6,16}$/);\r\n");
      out.write("\r\n");
      out.write("                if($inputMemberId.value == \"\") {\r\n");
      out.write("                    alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("                    $inputMemberId.focus();\r\n");
      out.write("                } else if(!regExp.test($inputMemberId.value)) {\r\n");
      out.write("                    alert(\"6자 이상 16자 이하의 영문 혹은 영문과 숫자를 조합\");\r\n");
      out.write("                    $inputMemberId.value = \"\";\r\n");
      out.write("                    $inputMemberId.focus();\r\n");
      out.write("                } else {\r\n");
      out.write("                    idCheck = true;\r\n");
      out.write("                   	\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("    					type: \"post\",\r\n");
      out.write("    					url: \"doubleIdCheckPro.jsp\",\r\n");
      out.write("    					data: {\r\n");
      out.write("    						id: $inputMemberId.value\r\n");
      out.write("    					},\r\n");
      out.write("    					success: function(data) {\r\n");
      out.write("    						let str = '<p id=\"check\">';\r\n");
      out.write("    						let length = str.length;\r\n");
      out.write("    						let startIndex = data.indexOf(str);\r\n");
      out.write("    						\r\n");
      out.write("    						let checkValue = data.substr(startIndex + length);\r\n");
      out.write("    						\r\n");
      out.write("    						console.log(\"data = \" + data);\r\n");
      out.write("    						console.log(\"length = \" + length);\r\n");
      out.write("    						console.log(\"startIndex = \" + startIndex);\r\n");
      out.write("    						console.log(\"[checkValue = \" + checkValue + \"]\");\r\n");
      out.write("    						\r\n");
      out.write("    						// 아이디가 중복되면\r\n");
      out.write("    						if(checkValue.trim() === \"-1\") {\r\n");
      out.write("    							alert(\"중복된 아이디입니다.\");\r\n");
      out.write("    							$inputMemberId.value = \"\";\r\n");
      out.write("    							$inputMemberId.focus();\r\n");
      out.write("    						} else {\r\n");
      out.write("    							alert(\"사용할 수 있는 아이디입니다.\");\r\n");
      out.write("    							\r\n");
      out.write("    							$inputMemberPw.focus();\r\n");
      out.write("    						}\r\n");
      out.write("    					},\r\n");
      out.write("    					error: function() {\r\n");
      out.write("    						alert(\"joinForm error\");\r\n");
      out.write("    					}\r\n");
      out.write("    				});	\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* 비밀번호 유효성 검사 */\r\n");
      out.write("            let inputMemberPwInput = (event) => {\r\n");
      out.write("                let $msgMemberPw = document.querySelector(\"#msg-memberPw\");\r\n");
      out.write("\r\n");
      out.write("                let regExp = RegExp(/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^*()\\-_=+\\\\\\|\\[\\]{};:\\'\",.<>\\/?]).{8,16}$/);\r\n");
      out.write("                if(regExp.test($inputMemberPw.value)) {\r\n");
      out.write("                    $msgMemberPw.innerHTML = \"\";\r\n");
      out.write("                } else {\r\n");
      out.write("                    $msgMemberPw.innerHTML = \"<span style='color:#F03F40; font-size:12px;'>영문 대문자와 소문자, 숫자, 특수문자를 하나 이상 포함하여 8~16자 조합</span>\";\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* 비밀번호확인 유효성 검사 */\r\n");
      out.write("            let inputMemberPwReInput = (event) => {\r\n");
      out.write("                let $msgMemberPwRe = document.querySelector(\"#msg-memberPwRe\");\r\n");
      out.write("\r\n");
      out.write("                if($inputMemberPw.value == $inputMemberPwRe.value) {\r\n");
      out.write("                    $msgMemberPwRe.innerHTML = \"\";\r\n");
      out.write("                } else {\r\n");
      out.write("                    $msgMemberPwRe.innerHTML = \"<span style='color:#F03F40; font-size:12px;'>동일한 비밀번호 입력</span>\";\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* 이름 유효성 검사 */\r\n");
      out.write("            let inputMemberNameInput = (event) => {\r\n");
      out.write("                let $msgMemberName = document.querySelector(\"#msg-memberName\");\r\n");
      out.write("\r\n");
      out.write("                let regExp = RegExp(/^[가-힣]{2,6}$/);\r\n");
      out.write("                if(regExp.test($inputMemberName.value)) {\r\n");
      out.write("                    $msgMemberName.innerHTML = \"\";\r\n");
      out.write("                } else {\r\n");
      out.write("                    $msgMemberName.innerHTML = \"<span style='color:#F03F40; font-size:12px;'>2~6글자의 한글만 입력</span>\";\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* 이메일 유효성 검사 */\r\n");
      out.write("            let inputMemberEmailInput = (event) => {\r\n");
      out.write("                let $msgMemberEmail = document.querySelector(\"#msg-memberEmail\");\r\n");
      out.write("\r\n");
      out.write("                let regExp = RegExp(/^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/);\r\n");
      out.write("                if(regExp.test($inputMemberEmail.value)) {\r\n");
      out.write("                    $msgMemberEmail.innerHTML = \"\";\r\n");
      out.write("                } else {\r\n");
      out.write("                    $msgMemberEmail.innerHTML = \"<span style='color:#F03F40; font-size:12px;'>이메일 형식으로 입력해 주세요.</span>\";\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* 이메일 중복검사 */\r\n");
      out.write("            let buttonMemberEmailCheckProClick = (event) => {\r\n");
      out.write("                let regExp = RegExp(/^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/);\r\n");
      out.write("                if($inputMemberEmail.value == \"\") {\r\n");
      out.write("                    alert(\"이메일을 입력해주세요.\");\r\n");
      out.write("                    $inputMemberEmail.focus();\r\n");
      out.write("                } else if(!regExp.test($inputMemberEmail.value)) {\r\n");
      out.write("                    alert(\"이메일 형식으로 입력해 주세요.\");\r\n");
      out.write("                    $inputMemberEmail.value = \"\";\r\n");
      out.write("                    $inputMemberEmail.focus();\r\n");
      out.write("                } else {\r\n");
      out.write("                    emailCheck = true;\r\n");
      out.write("\r\n");
      out.write("                	$.ajax({\r\n");
      out.write("    					type: \"post\",\r\n");
      out.write("    					url: \"doubleEmailCheckPro.jsp\",\r\n");
      out.write("    					data: {\r\n");
      out.write("    						email: $inputMemberEmail.value\r\n");
      out.write("    					},\r\n");
      out.write("    					success: function(data) {\r\n");
      out.write("    						let str = '<p id=\"check\">';\r\n");
      out.write("    						let length = str.length;\r\n");
      out.write("    						let startIndex = data.indexOf(str);\r\n");
      out.write("    						\r\n");
      out.write("    						let checkValue = data.substr(startIndex + length);\r\n");
      out.write("    						\r\n");
      out.write("    						console.log(\"data = \" + data);\r\n");
      out.write("    						console.log(\"length = \" + length);\r\n");
      out.write("    						console.log(\"startIndex = \" + startIndex);\r\n");
      out.write("    						console.log(\"checkValue = \" + checkValue);\r\n");
      out.write("    						\r\n");
      out.write("    						// 이메일이 중복되면\r\n");
      out.write("    						if(checkValue === \"-1\") {\r\n");
      out.write("    							alert(\"중복된 이메일입니다.\");\r\n");
      out.write("    							$inputMemberEmail.value=\"\";\r\n");
      out.write("    							$inputMemberEmail.focus();\r\n");
      out.write("    						} else {\r\n");
      out.write("    							alert(\"사용할 수 있는 이메일입니다.\");\r\n");
      out.write("    						}\r\n");
      out.write("    					},\r\n");
      out.write("    					error: function() {\r\n");
      out.write("    						alert(\"joinForm error\");\r\n");
      out.write("    					}\r\n");
      out.write("    				});\r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* 휴대폰 유효성 검사 */\r\n");
      out.write("            let inputMemberPhoneInput = (event) => {\r\n");
      out.write("                let $msgMemberPhone = document.querySelector(\"#msg-memberPhone\");\r\n");
      out.write("\r\n");
      out.write("                let regExp = RegExp(/^01([0|1|6|7|8|9])([0-9]{3,4})([0-9]{4})$/);\r\n");
      out.write("                if(regExp.test($inputMemberPhone.value)) {\r\n");
      out.write("                    $msgMemberPhone.innerHTML = \"\";\r\n");
      out.write("                } else {\r\n");
      out.write("                    $msgMemberPhone.innerHTML = \"<span style='color:#F03F40; font-size:12px;'>휴대폰 형식으로 입력해 주세요.</span>\";\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* 우편번호 검색 기능 */\r\n");
      out.write("            let execDaumPostcode = (event) => {\r\n");
      out.write("                new daum.Postcode( {\r\n");
      out.write("                    oncomplete: function(data) {\r\n");
      out.write("\r\n");
      out.write("                        document.querySelector(\"#input-memberAddr1\").value = data.zonecode;\r\n");
      out.write("                        document.querySelector(\"#input-memberAddr2\").value = data.address;\r\n");
      out.write("\r\n");
      out.write("                        document.querySelector(\"#input-memberAddr3\").focus();\r\n");
      out.write("                    }\r\n");
      out.write("                } ).open();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* 전체동의 체크 자동화 기능 */\r\n");
      out.write("            let checkMemberAllTermsClick = (event) => {\r\n");
      out.write("                if($checkMemberAllTerms.checked) {\r\n");
      out.write("                    for(let i=0; i<$checkMemberTerms.length; i++) {\r\n");
      out.write("                        $checkMemberTerms[i].checked = true;\r\n");
      out.write("                    }\r\n");
      out.write("                } else {\r\n");
      out.write("                    for(let i=0; i<$checkMemberTerms.length; i++) {\r\n");
      out.write("                        $checkMemberTerms[i].checked = false;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            let checkMemberTermsClick = (event) => {\r\n");
      out.write("                let count = 0;\r\n");
      out.write("                for(let i=0; i<$checkMemberTerms.length; i++) {\r\n");
      out.write("                    if($checkMemberTerms[i].checked) {\r\n");
      out.write("                        count += 1;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                if(count == $checkMemberTerms.length) {\r\n");
      out.write("                    $checkMemberAllTerms.checked = true;\r\n");
      out.write("                } else {\r\n");
      out.write("                    $checkMemberAllTerms.checked = false;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* 가입하기 */\r\n");
      out.write("            let buttonMemberJoinProClick = (event) => {\r\n");
      out.write("                // 아이디 입력 확인\r\n");
      out.write("                if($inputMemberId.value == \"\") {\r\n");
      out.write("                    $inputMemberId.focus();\r\n");
      out.write("                    alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                // 아이디 중복확인\r\n");
      out.write("                if(idCheck == false) {\r\n");
      out.write("                    alert(\"아이디를 중복확인을 해주세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                // 비밀번호 입력 확인\r\n");
      out.write("                if($inputMemberPw.value == \"\") {\r\n");
      out.write("                    alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                // 비밀번호확인 입력 확인\r\n");
      out.write("                if($inputMemberPwRe.value == \"\") {\r\n");
      out.write("                    alert(\"비밀번호 확인을 입력해주세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                // 이름 입력 확인\r\n");
      out.write("                if($inputMemberName.value == \"\") {\r\n");
      out.write("                    alert(\"이름을 입력해주세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                // 이메일 입력 확인\r\n");
      out.write("                if($inputMemberEmail.value == \"\") {\r\n");
      out.write("                    alert(\"이메일을 입력하세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                // 이메일 중복확인\r\n");
      out.write("                if(emailCheck == false) {\r\n");
      out.write("                    alert(\"이메일 중복 확인를 해주세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                // 휴대폰 입력 확인\r\n");
      out.write("                if($inputMemberPhone.value == \"\") {\r\n");
      out.write("                    alert(\"휴대폰 번호를 입력해주세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                // 우편번호 입력 확인\r\n");
      out.write("                if($inputMemberAddr1.value == \"\") {\r\n");
      out.write("                    alert(\"우편번호를 입력해주세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                // 도로명 입력 확인\r\n");
      out.write("                if($inputMemberAddr2.value == \"\") {\r\n");
      out.write("                    alert(\"도로명을 입력해주세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                // 남은 주소 입력 확인\r\n");
      out.write("                if($inputMemberAddr3.value == \"\") {\r\n");
      out.write("                    alert(\"남은 주소를 입력해주세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                let $radioMemberGenderList = document.querySelectorAll(\".radio-memberGender\");\r\n");
      out.write("                let memberGender = \"\";\r\n");
      out.write("                for(let i=0; i<$radioMemberGenderList.length; i++) {\r\n");
      out.write("                	if($radioMemberGenderList[i].checked) {\r\n");
      out.write("                		memberGender = $radioMemberGenderList[i].value;\r\n");
      out.write("                	}\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                // 이용약관 동의 필수항목 선택 확인\r\n");
      out.write("                let $checkMemberTerms = document.querySelectorAll(\".check-memberTerms\");\r\n");
      out.write("                let checkResult = true;\r\n");
      out.write("                for(let i=0; i<$checkMemberTerms.length - 1; i++) {\r\n");
      out.write("                    if(!$checkMemberTerms[i].checked) {\r\n");
      out.write("                        checkResult = false;\r\n");
      out.write("                        break;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                if(checkResult == false) {\r\n");
      out.write("                    alert(\"필수 약관에 동의해주세요.\");\r\n");
      out.write("                    return false;\r\n");
      out.write("                } \r\n");
      out.write("                \r\n");
      out.write("                let selectCheckTerm = 0;\r\n");
      out.write("                if($selectMemberTerm.checked) {\r\n");
      out.write("                	selectCheckTerm = 1;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("      \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("    			$.ajax({\r\n");
      out.write("    				type: \"post\",\r\n");
      out.write("    				url: \"joinPro.jsp\",\r\n");
      out.write("    				data: {\r\n");
      out.write("    					\r\n");
      out.write("    					id : $inputMemberId.value,					\r\n");
      out.write("    					pw  : $inputMemberPw.value,\r\n");
      out.write("    					name : $inputMemberName.value,\r\n");
      out.write("    					email : $inputMemberEmail.value,\r\n");
      out.write("    					phone : $inputMemberPhone.value,\r\n");
      out.write("    					addr1 : $inputMemberAddr1.value,\r\n");
      out.write("    					addr2 : $inputMemberAddr2.value,\r\n");
      out.write("    					addr3 : $inputMemberAddr3.value,	\r\n");
      out.write("    					gender : memberGender,\r\n");
      out.write("    					route : $selectMemberRoute.value,\r\n");
      out.write("    					marketing : selectCheckTerm\r\n");
      out.write("    					\r\n");
      out.write("    				},\r\n");
      out.write("    				success: function(data) {\r\n");
      out.write("    					alert(\"회원가입 성공\");\r\n");
      out.write("    					location.href=\"main.jsp\";\r\n");
      out.write("    				},\r\n");
      out.write("    				error: function() {\r\n");
      out.write("    					alert(\"joinForm error\");\r\n");
      out.write("    				}\r\n");
      out.write("    			});\r\n");
      out.write("    			         \r\n");
      out.write("                return true;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            //--------------------------------------------------------------------------------------\r\n");
      out.write("\r\n");
      out.write("            let idCheck = false;\r\n");
      out.write("            let emailCheck = false;\r\n");
      out.write("\r\n");
      out.write("            let $inputMemberId = document.querySelector(\"#input-memberId\");\r\n");
      out.write("            $inputMemberId.addEventListener(\"input\", inputMemberIdInput);\r\n");
      out.write("\r\n");
      out.write("            let $buttonMemberIdCheckPro = document.querySelector(\"#button-memberIdCheckPro\");\r\n");
      out.write("            $buttonMemberIdCheckPro.addEventListener(\"click\", buttonMemberIdCheckProClick);\r\n");
      out.write("\r\n");
      out.write("            let $inputMemberPw = document.querySelector(\"#input-memberPw\");\r\n");
      out.write("            $inputMemberPw.addEventListener(\"input\", inputMemberPwInput);\r\n");
      out.write("\r\n");
      out.write("            let $inputMemberPwRe = document.querySelector(\"#input-memberPwRe\");\r\n");
      out.write("            $inputMemberPwRe.addEventListener(\"input\", inputMemberPwReInput);\r\n");
      out.write("\r\n");
      out.write("            let $inputMemberName = document.querySelector(\"#input-memberName\");\r\n");
      out.write("            $inputMemberName.addEventListener(\"input\", inputMemberNameInput);\r\n");
      out.write("\r\n");
      out.write("            let $inputMemberEmail = document.querySelector(\"#input-memberEmail\");\r\n");
      out.write("            $inputMemberEmail.addEventListener(\"input\", inputMemberEmailInput);\r\n");
      out.write("\r\n");
      out.write("            let $buttonMemberEmailCheckPro = document.querySelector(\"#button-memberEmailCheckPro\");\r\n");
      out.write("            $buttonMemberEmailCheckPro.addEventListener(\"click\", buttonMemberEmailCheckProClick);\r\n");
      out.write("\r\n");
      out.write("            let $inputMemberPhone = document.querySelector(\"#input-memberPhone\");\r\n");
      out.write("            $inputMemberPhone.addEventListener(\"input\", inputMemberPhoneInput);\r\n");
      out.write("\r\n");
      out.write("            let $inputMemberAddr1 = document.querySelector(\"#input-memberAddr1\");\r\n");
      out.write("            let $inputMemberAddr2 = document.querySelector(\"#input-memberAddr2\");\r\n");
      out.write("            let $inputMemberAddr3 = document.querySelector(\"#input-memberAddr3\");\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            let $selectMemberRoute = document.querySelector(\"#select-memberRoute\");\r\n");
      out.write("\r\n");
      out.write("            let $checkMemberAllTerms = document.querySelector(\"#check-memberAllTerms\");\r\n");
      out.write("            $checkMemberAllTerms.addEventListener(\"click\", checkMemberAllTermsClick);\r\n");
      out.write("\r\n");
      out.write("            let $checkMemberTerms = document.querySelectorAll(\".check-memberTerms\");\r\n");
      out.write("            for(let i=0; i<$checkMemberTerms.length; i++) {\r\n");
      out.write("                $checkMemberTerms[i].addEventListener(\"click\", checkMemberTermsClick);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            let $selectMemberTerm = document.querySelector(\".select-memberTerm\");\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            let $btnMemberJoinPro = document.querySelector(\"#button-memberJoinPro\");\r\n");
      out.write("            $btnMemberJoinPro.addEventListener(\"click\", buttonMemberJoinProClick);\r\n");
      out.write("    	\r\n");
      out.write("    </script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
